version: '3.9'

services:
  mongo:
    image: mongo:latest
    container_name: newsMongoDB
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - .data/mongo:/data/db
    networks:
      - meetupNetwork
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWD}

  newsZookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: newsZookeeper
    restart: unless-stopped
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - meetupNetwork

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: newsKafka
    restart: unless-stopped
    depends_on:
      - newsZookeeper
    networks:
      - meetupNetwork
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: newsZookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  workdir:
    image: python:3.11-slim
    container_name: newsWorkDir
    volumes:
      - ./src:/src
    command: bash -c "cd /src && pip install -r requirements.txt && bash run_scripts.sh && tail -f /dev/null"
    networks:
      - meetupNetwork
    depends_on:
      - kafka
      - mongo
      - newsZookeeper

volumes:
  mongo:
  src:

networks:
  meetupNetwork:
    driver: bridge

